; PlatformIO Project Configuration File

[platformio]
default_envs = wheel_module
src_dir = .

[common]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -Icommon/include
    -std=gnu++17
    -O2

[env:wheel_module]
extends = common
build_flags = 
    ${common.build_flags}
    -Iwheel_module/src
    -L ./precompiled_lib
    -lthird_eye_lib
    ;-lthird_eye_lib_logs    ; for lib version with logs 
build_src_filter = 
    +<wheel_module/src/>
    +<common/src/>
lib_deps = 
    h2zero/NimBLE-Arduino@^2.2.0

[env:led_module]
extends = common
build_flags = 
    ${common.build_flags}
    -Iled_module/src
build_src_filter = 
    +<led_module/src/>
    +<common/src/>
lib_deps = 
    h2zero/NimBLE-Arduino@^2.2.0
    fastled/FastLED@^3.9.0
    
[env:extension_device_test]
extends = common
build_flags = 
    ${common.build_flags}
    -Iextension_device_test/src
build_src_filter = 
    +<extension_device_test/src/>
    +<common/src/extention_server_handler.cpp>
    +<common/src/ble_manager.cpp>
lib_deps = 
    h2zero/NimBLE-Arduino@^2.2.0
